### ISSUE TITLE
Advent Rising is not recognized by the script.

### ISSUE THREAD

**Issue by wof8317** [ZOOM-Platform/zoom-platform.sh#1]
When I try to install Advent Rising using this wonderful script, it thinks that it is not a ZOOM Platform installer (even though it is). 

It could be that it is a multipart installer, as all the ones I tried were single executable installers and not the ones with multiple bin files.

**Comment by doZennn** [comment]
This has nothing to do with it being multi-part. Some pre-2020 installers don't have the metadata this script needs to apply the correct protonfixes.

We'll update this game and close this once it's live.

**Comment by doZennn** [comment]
The installer has been updated, you'll need to re-download all the parts again.

**Comment by wof8317** [comment]
Thanks.
